// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Info
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Vec2Int : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Vec2Int __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int X { get { return __p.bb.GetInt(__p.bb_pos + 0); } }
  public int Y { get { return __p.bb.GetInt(__p.bb_pos + 4); } }

  public static Offset<Info.Vec2Int> CreateVec2Int(FlatBufferBuilder builder, int X, int Y) {
    builder.Prep(4, 8);
    builder.PutInt(Y);
    builder.PutInt(X);
    return new Offset<Info.Vec2Int>(builder.Offset);
  }
  public Vec2IntT UnPack() {
    var _o = new Vec2IntT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(Vec2IntT _o) {
    _o.X = this.X;
    _o.Y = this.Y;
  }
  public static Offset<Info.Vec2Int> Pack(FlatBufferBuilder builder, Vec2IntT _o) {
    if (_o == null) return default(Offset<Info.Vec2Int>);
    return CreateVec2Int(
      builder,
      _o.X,
      _o.Y);
  }
};

public class Vec2IntT
{
  public int X { get; set; }
  public int Y { get; set; }

  public Vec2IntT() {
    this.X = 0;
    this.Y = 0;
  }
}

public struct PositionInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static PositionInfo GetRootAsPositionInfo(ByteBuffer _bb) { return GetRootAsPositionInfo(_bb, new PositionInfo()); }
  public static PositionInfo GetRootAsPositionInfo(ByteBuffer _bb, PositionInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PositionInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Info.Vec2Int? Pos { get { int o = __p.__offset(4); return o != 0 ? (Info.Vec2Int?)(new Info.Vec2Int()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Define.CreatureState State { get { int o = __p.__offset(6); return o != 0 ? (Define.CreatureState)__p.bb.Get(o + __p.bb_pos) : Define.CreatureState.IDLE; } }
  public Define.Dir MoveDir { get { int o = __p.__offset(8); return o != 0 ? (Define.Dir)__p.bb.Get(o + __p.bb_pos) : Define.Dir.UP; } }

  public static Offset<Info.PositionInfo> CreatePositionInfo(FlatBufferBuilder builder,
      Info.Vec2IntT pos = null,
      Define.CreatureState state = Define.CreatureState.IDLE,
      Define.Dir move_dir = Define.Dir.UP) {
    builder.StartTable(3);
    PositionInfo.AddPos(builder, Info.Vec2Int.Pack(builder, pos));
    PositionInfo.AddMoveDir(builder, move_dir);
    PositionInfo.AddState(builder, state);
    return PositionInfo.EndPositionInfo(builder);
  }

  public static void StartPositionInfo(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddPos(FlatBufferBuilder builder, Offset<Info.Vec2Int> posOffset) { builder.AddStruct(0, posOffset.Value, 0); }
  public static void AddState(FlatBufferBuilder builder, Define.CreatureState state) { builder.AddByte(1, (byte)state, 0); }
  public static void AddMoveDir(FlatBufferBuilder builder, Define.Dir moveDir) { builder.AddByte(2, (byte)moveDir, 0); }
  public static Offset<Info.PositionInfo> EndPositionInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Info.PositionInfo>(o);
  }
  public PositionInfoT UnPack() {
    var _o = new PositionInfoT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(PositionInfoT _o) {
    _o.Pos = this.Pos.HasValue ? this.Pos.Value.UnPack() : null;
    _o.State = this.State;
    _o.MoveDir = this.MoveDir;
  }
  public static Offset<Info.PositionInfo> Pack(FlatBufferBuilder builder, PositionInfoT _o) {
    if (_o == null) return default(Offset<Info.PositionInfo>);
    return CreatePositionInfo(
      builder,
      _o.Pos,
      _o.State,
      _o.MoveDir);
  }
};

public class PositionInfoT
{
  public Info.Vec2IntT Pos { get; set; }
  public Define.CreatureState State { get; set; }
  public Define.Dir MoveDir { get; set; }

  public PositionInfoT() {
    this.Pos = new Info.Vec2IntT();
    this.State = Define.CreatureState.IDLE;
    this.MoveDir = Define.Dir.UP;
  }
}


}
