// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DEFINEPROTOCOL_DEFINE_H_
#define FLATBUFFERS_GENERATED_DEFINEPROTOCOL_DEFINE_H_

#include "flatbuffers/flatbuffers.h"

namespace Define {

enum Job : uint8_t {
  Job_WARRIOR = 0,
  Job_ARCHER = 1,
  Job_SORCERER = 2,
  Job_DUELIST = 3,
  Job_MIN = Job_WARRIOR,
  Job_MAX = Job_DUELIST
};

inline const Job (&EnumValuesJob())[4] {
  static const Job values[] = {
    Job_WARRIOR,
    Job_ARCHER,
    Job_SORCERER,
    Job_DUELIST
  };
  return values;
}

inline const char * const *EnumNamesJob() {
  static const char * const names[5] = {
    "WARRIOR",
    "ARCHER",
    "SORCERER",
    "DUELIST",
    nullptr
  };
  return names;
}

inline const char *EnumNameJob(Job e) {
  if (flatbuffers::IsOutRange(e, Job_WARRIOR, Job_DUELIST)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesJob()[index];
}

enum AccountLimit : uint8_t {
  AccountLimit_MinIDLen = 2,
  AccountLimit_MinPasswordLen = 4,
  AccountLimit_MaxIDLen = 10,
  AccountLimit_MaxPasswordLen = 15,
  AccountLimit_MIN = AccountLimit_MinIDLen,
  AccountLimit_MAX = AccountLimit_MaxPasswordLen
};

inline const AccountLimit (&EnumValuesAccountLimit())[4] {
  static const AccountLimit values[] = {
    AccountLimit_MinIDLen,
    AccountLimit_MinPasswordLen,
    AccountLimit_MaxIDLen,
    AccountLimit_MaxPasswordLen
  };
  return values;
}

inline const char * const *EnumNamesAccountLimit() {
  static const char * const names[15] = {
    "MinIDLen",
    "",
    "MinPasswordLen",
    "",
    "",
    "",
    "",
    "",
    "MaxIDLen",
    "",
    "",
    "",
    "",
    "MaxPasswordLen",
    nullptr
  };
  return names;
}

inline const char *EnumNameAccountLimit(AccountLimit e) {
  if (flatbuffers::IsOutRange(e, AccountLimit_MinIDLen, AccountLimit_MaxPasswordLen)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(AccountLimit_MinIDLen);
  return EnumNamesAccountLimit()[index];
}

enum CharacterLimit : uint8_t {
  CharacterLimit_MinNameLen = 1,
  CharacterLimit_EmptyCharacterSlot = 3,
  CharacterLimit_MaxCharacterSlot = 5,
  CharacterLimit_MaxNameLen = 8,
  CharacterLimit_MIN = CharacterLimit_MinNameLen,
  CharacterLimit_MAX = CharacterLimit_MaxNameLen
};

inline const CharacterLimit (&EnumValuesCharacterLimit())[4] {
  static const CharacterLimit values[] = {
    CharacterLimit_MinNameLen,
    CharacterLimit_EmptyCharacterSlot,
    CharacterLimit_MaxCharacterSlot,
    CharacterLimit_MaxNameLen
  };
  return values;
}

inline const char * const *EnumNamesCharacterLimit() {
  static const char * const names[9] = {
    "MinNameLen",
    "",
    "EmptyCharacterSlot",
    "",
    "MaxCharacterSlot",
    "",
    "",
    "MaxNameLen",
    nullptr
  };
  return names;
}

inline const char *EnumNameCharacterLimit(CharacterLimit e) {
  if (flatbuffers::IsOutRange(e, CharacterLimit_MinNameLen, CharacterLimit_MaxNameLen)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(CharacterLimit_MinNameLen);
  return EnumNamesCharacterLimit()[index];
}

enum StatType : uint8_t {
  StatType_STR = 0,
  StatType_DEX = 1,
  StatType_INT = 2,
  StatType_MIN = StatType_STR,
  StatType_MAX = StatType_INT
};

inline const StatType (&EnumValuesStatType())[3] {
  static const StatType values[] = {
    StatType_STR,
    StatType_DEX,
    StatType_INT
  };
  return values;
}

inline const char * const *EnumNamesStatType() {
  static const char * const names[4] = {
    "STR",
    "DEX",
    "INT",
    nullptr
  };
  return names;
}

inline const char *EnumNameStatType(StatType e) {
  if (flatbuffers::IsOutRange(e, StatType_STR, StatType_INT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesStatType()[index];
}

enum GearType : uint8_t {
  GearType_LEFT_HAND = 0,
  GearType_RIGHT_HAND = 1,
  GearType_ARMOR = 2,
  GearType_HELMET = 3,
  GearType_SHOULDER = 4,
  GearType_ARM = 5,
  GearType_FEET = 6,
  GearType_HAIR = 7,
  GearType_FACE = 8,
  GearType_MIN = GearType_LEFT_HAND,
  GearType_MAX = GearType_FACE
};

inline const GearType (&EnumValuesGearType())[9] {
  static const GearType values[] = {
    GearType_LEFT_HAND,
    GearType_RIGHT_HAND,
    GearType_ARMOR,
    GearType_HELMET,
    GearType_SHOULDER,
    GearType_ARM,
    GearType_FEET,
    GearType_HAIR,
    GearType_FACE
  };
  return values;
}

inline const char * const *EnumNamesGearType() {
  static const char * const names[10] = {
    "LEFT_HAND",
    "RIGHT_HAND",
    "ARMOR",
    "HELMET",
    "SHOULDER",
    "ARM",
    "FEET",
    "HAIR",
    "FACE",
    nullptr
  };
  return names;
}

inline const char *EnumNameGearType(GearType e) {
  if (flatbuffers::IsOutRange(e, GearType_LEFT_HAND, GearType_FACE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesGearType()[index];
}

enum Dir : uint8_t {
  Dir_UP = 0,
  Dir_DOWN = 1,
  Dir_LEFT = 2,
  Dir_RIGHT = 3,
  Dir_MIN = Dir_UP,
  Dir_MAX = Dir_RIGHT
};

inline const Dir (&EnumValuesDir())[4] {
  static const Dir values[] = {
    Dir_UP,
    Dir_DOWN,
    Dir_LEFT,
    Dir_RIGHT
  };
  return values;
}

inline const char * const *EnumNamesDir() {
  static const char * const names[5] = {
    "UP",
    "DOWN",
    "LEFT",
    "RIGHT",
    nullptr
  };
  return names;
}

inline const char *EnumNameDir(Dir e) {
  if (flatbuffers::IsOutRange(e, Dir_UP, Dir_RIGHT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDir()[index];
}

enum CreatureState : uint8_t {
  CreatureState_IDLE = 0,
  CreatureState_WALK = 1,
  CreatureState_RUN = 2,
  CreatureState_JUMP = 3,
  CreatureState_SKILL = 4,
  CreatureState_DEAD = 5,
  CreatureState_MIN = CreatureState_IDLE,
  CreatureState_MAX = CreatureState_DEAD
};

inline const CreatureState (&EnumValuesCreatureState())[6] {
  static const CreatureState values[] = {
    CreatureState_IDLE,
    CreatureState_WALK,
    CreatureState_RUN,
    CreatureState_JUMP,
    CreatureState_SKILL,
    CreatureState_DEAD
  };
  return values;
}

inline const char * const *EnumNamesCreatureState() {
  static const char * const names[7] = {
    "IDLE",
    "WALK",
    "RUN",
    "JUMP",
    "SKILL",
    "DEAD",
    nullptr
  };
  return names;
}

inline const char *EnumNameCreatureState(CreatureState e) {
  if (flatbuffers::IsOutRange(e, CreatureState_IDLE, CreatureState_DEAD)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCreatureState()[index];
}

}  // namespace Define

#endif  // FLATBUFFERS_GENERATED_DEFINEPROTOCOL_DEFINE_H_
