// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LOGINPROTOCOL_LOGINPACKET_H_
#define FLATBUFFERS_GENERATED_LOGINPROTOCOL_LOGINPACKET_H_

#include "flatbuffers/flatbuffers.h"

#include "define_protocol_generated.h"

namespace LoginPacket {

struct CS_LOGIN_REQ;
struct CS_LOGIN_REQBuilder;
struct CS_LOGIN_REQT;

struct CHARACTER_INFO;
struct CHARACTER_INFOBuilder;
struct CHARACTER_INFOT;

struct SC_LOGIN_RES;
struct SC_LOGIN_RESBuilder;
struct SC_LOGIN_REST;

struct SC_PING_REQ;
struct SC_PING_REQBuilder;
struct SC_PING_REQT;

struct CS_PING_RES;
struct CS_PING_RESBuilder;
struct CS_PING_REST;

struct CS_LOGOUT_NOTI;
struct CS_LOGOUT_NOTIBuilder;
struct CS_LOGOUT_NOTIT;

struct CS_CREATE_CHARACTER_REQ;
struct CS_CREATE_CHARACTER_REQBuilder;
struct CS_CREATE_CHARACTER_REQT;

struct SC_CREATE_CHARACTER_RES;
struct SC_CREATE_CHARACTER_RESBuilder;
struct SC_CREATE_CHARACTER_REST;

struct Root;
struct RootBuilder;
struct RootT;

enum ErrorCode : int8_t {
  ErrorCode_SUCCESS = 0,
  ErrorCode_UNKNOWN = 1,
  ErrorCode_ALREADY_LOGINED = 2,
  ErrorCode_MIN = ErrorCode_SUCCESS,
  ErrorCode_MAX = ErrorCode_ALREADY_LOGINED
};

inline const ErrorCode (&EnumValuesErrorCode())[3] {
  static const ErrorCode values[] = {
    ErrorCode_SUCCESS,
    ErrorCode_UNKNOWN,
    ErrorCode_ALREADY_LOGINED
  };
  return values;
}

inline const char * const *EnumNamesErrorCode() {
  static const char * const names[4] = {
    "SUCCESS",
    "UNKNOWN",
    "ALREADY_LOGINED",
    nullptr
  };
  return names;
}

inline const char *EnumNameErrorCode(ErrorCode e) {
  if (flatbuffers::IsOutRange(e, ErrorCode_SUCCESS, ErrorCode_ALREADY_LOGINED)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesErrorCode()[index];
}

enum Packet : uint8_t {
  Packet_NONE = 0,
  Packet_CS_LOGIN_REQ = 1,
  Packet_SC_LOGIN_RES = 2,
  Packet_SC_PING_REQ = 3,
  Packet_CS_PING_RES = 4,
  Packet_CS_LOGOUT_NOTI = 5,
  Packet_CS_CREATE_CHARACTER_REQ = 6,
  Packet_SC_CREATE_CHARACTER_RES = 7,
  Packet_MIN = Packet_NONE,
  Packet_MAX = Packet_SC_CREATE_CHARACTER_RES
};

inline const Packet (&EnumValuesPacket())[8] {
  static const Packet values[] = {
    Packet_NONE,
    Packet_CS_LOGIN_REQ,
    Packet_SC_LOGIN_RES,
    Packet_SC_PING_REQ,
    Packet_CS_PING_RES,
    Packet_CS_LOGOUT_NOTI,
    Packet_CS_CREATE_CHARACTER_REQ,
    Packet_SC_CREATE_CHARACTER_RES
  };
  return values;
}

inline const char * const *EnumNamesPacket() {
  static const char * const names[9] = {
    "NONE",
    "CS_LOGIN_REQ",
    "SC_LOGIN_RES",
    "SC_PING_REQ",
    "CS_PING_RES",
    "CS_LOGOUT_NOTI",
    "CS_CREATE_CHARACTER_REQ",
    "SC_CREATE_CHARACTER_RES",
    nullptr
  };
  return names;
}

inline const char *EnumNamePacket(Packet e) {
  if (flatbuffers::IsOutRange(e, Packet_NONE, Packet_SC_CREATE_CHARACTER_RES)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPacket()[index];
}

template<typename T> struct PacketTraits {
  static const Packet enum_value = Packet_NONE;
};

template<> struct PacketTraits<LoginPacket::CS_LOGIN_REQ> {
  static const Packet enum_value = Packet_CS_LOGIN_REQ;
};

template<> struct PacketTraits<LoginPacket::SC_LOGIN_RES> {
  static const Packet enum_value = Packet_SC_LOGIN_RES;
};

template<> struct PacketTraits<LoginPacket::SC_PING_REQ> {
  static const Packet enum_value = Packet_SC_PING_REQ;
};

template<> struct PacketTraits<LoginPacket::CS_PING_RES> {
  static const Packet enum_value = Packet_CS_PING_RES;
};

template<> struct PacketTraits<LoginPacket::CS_LOGOUT_NOTI> {
  static const Packet enum_value = Packet_CS_LOGOUT_NOTI;
};

template<> struct PacketTraits<LoginPacket::CS_CREATE_CHARACTER_REQ> {
  static const Packet enum_value = Packet_CS_CREATE_CHARACTER_REQ;
};

template<> struct PacketTraits<LoginPacket::SC_CREATE_CHARACTER_RES> {
  static const Packet enum_value = Packet_SC_CREATE_CHARACTER_RES;
};

struct PacketUnion {
  Packet type;
  void *value;

  PacketUnion() : type(Packet_NONE), value(nullptr) {}
  PacketUnion(PacketUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(Packet_NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  PacketUnion(const PacketUnion &);
  PacketUnion &operator=(const PacketUnion &u)
    { PacketUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  PacketUnion &operator=(PacketUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~PacketUnion() { Reset(); }

  void Reset();

#ifndef FLATBUFFERS_CPP98_STL
  template <typename T>
  void Set(T&& val) {
    using RT = typename std::remove_reference<T>::type;
    Reset();
    type = PacketTraits<typename RT::TableType>::enum_value;
    if (type != Packet_NONE) {
      value = new RT(std::forward<T>(val));
    }
  }
#endif  // FLATBUFFERS_CPP98_STL

  static void *UnPack(const void *obj, Packet type, const flatbuffers::resolver_function_t *resolver);
  flatbuffers::Offset<void> Pack(flatbuffers::FlatBufferBuilder &_fbb, const flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  LoginPacket::CS_LOGIN_REQT *AsCS_LOGIN_REQ() {
    return type == Packet_CS_LOGIN_REQ ?
      reinterpret_cast<LoginPacket::CS_LOGIN_REQT *>(value) : nullptr;
  }
  const LoginPacket::CS_LOGIN_REQT *AsCS_LOGIN_REQ() const {
    return type == Packet_CS_LOGIN_REQ ?
      reinterpret_cast<const LoginPacket::CS_LOGIN_REQT *>(value) : nullptr;
  }
  LoginPacket::SC_LOGIN_REST *AsSC_LOGIN_RES() {
    return type == Packet_SC_LOGIN_RES ?
      reinterpret_cast<LoginPacket::SC_LOGIN_REST *>(value) : nullptr;
  }
  const LoginPacket::SC_LOGIN_REST *AsSC_LOGIN_RES() const {
    return type == Packet_SC_LOGIN_RES ?
      reinterpret_cast<const LoginPacket::SC_LOGIN_REST *>(value) : nullptr;
  }
  LoginPacket::SC_PING_REQT *AsSC_PING_REQ() {
    return type == Packet_SC_PING_REQ ?
      reinterpret_cast<LoginPacket::SC_PING_REQT *>(value) : nullptr;
  }
  const LoginPacket::SC_PING_REQT *AsSC_PING_REQ() const {
    return type == Packet_SC_PING_REQ ?
      reinterpret_cast<const LoginPacket::SC_PING_REQT *>(value) : nullptr;
  }
  LoginPacket::CS_PING_REST *AsCS_PING_RES() {
    return type == Packet_CS_PING_RES ?
      reinterpret_cast<LoginPacket::CS_PING_REST *>(value) : nullptr;
  }
  const LoginPacket::CS_PING_REST *AsCS_PING_RES() const {
    return type == Packet_CS_PING_RES ?
      reinterpret_cast<const LoginPacket::CS_PING_REST *>(value) : nullptr;
  }
  LoginPacket::CS_LOGOUT_NOTIT *AsCS_LOGOUT_NOTI() {
    return type == Packet_CS_LOGOUT_NOTI ?
      reinterpret_cast<LoginPacket::CS_LOGOUT_NOTIT *>(value) : nullptr;
  }
  const LoginPacket::CS_LOGOUT_NOTIT *AsCS_LOGOUT_NOTI() const {
    return type == Packet_CS_LOGOUT_NOTI ?
      reinterpret_cast<const LoginPacket::CS_LOGOUT_NOTIT *>(value) : nullptr;
  }
  LoginPacket::CS_CREATE_CHARACTER_REQT *AsCS_CREATE_CHARACTER_REQ() {
    return type == Packet_CS_CREATE_CHARACTER_REQ ?
      reinterpret_cast<LoginPacket::CS_CREATE_CHARACTER_REQT *>(value) : nullptr;
  }
  const LoginPacket::CS_CREATE_CHARACTER_REQT *AsCS_CREATE_CHARACTER_REQ() const {
    return type == Packet_CS_CREATE_CHARACTER_REQ ?
      reinterpret_cast<const LoginPacket::CS_CREATE_CHARACTER_REQT *>(value) : nullptr;
  }
  LoginPacket::SC_CREATE_CHARACTER_REST *AsSC_CREATE_CHARACTER_RES() {
    return type == Packet_SC_CREATE_CHARACTER_RES ?
      reinterpret_cast<LoginPacket::SC_CREATE_CHARACTER_REST *>(value) : nullptr;
  }
  const LoginPacket::SC_CREATE_CHARACTER_REST *AsSC_CREATE_CHARACTER_RES() const {
    return type == Packet_SC_CREATE_CHARACTER_RES ?
      reinterpret_cast<const LoginPacket::SC_CREATE_CHARACTER_REST *>(value) : nullptr;
  }
};

bool VerifyPacket(flatbuffers::Verifier &verifier, const void *obj, Packet type);
bool VerifyPacketVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

struct CS_LOGIN_REQT : public flatbuffers::NativeTable {
  typedef CS_LOGIN_REQ TableType;
  int64_t uid = 0;
  int32_t token = 0;
};

struct CS_LOGIN_REQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef CS_LOGIN_REQT NativeTableType;
  typedef CS_LOGIN_REQBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UID = 4,
    VT_TOKEN = 6
  };
  int64_t uid() const {
    return GetField<int64_t>(VT_UID, 0);
  }
  int32_t token() const {
    return GetField<int32_t>(VT_TOKEN, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_UID) &&
           VerifyField<int32_t>(verifier, VT_TOKEN) &&
           verifier.EndTable();
  }
  CS_LOGIN_REQT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CS_LOGIN_REQT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<CS_LOGIN_REQ> Pack(flatbuffers::FlatBufferBuilder &_fbb, const CS_LOGIN_REQT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CS_LOGIN_REQBuilder {
  typedef CS_LOGIN_REQ Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_uid(int64_t uid) {
    fbb_.AddElement<int64_t>(CS_LOGIN_REQ::VT_UID, uid, 0);
  }
  void add_token(int32_t token) {
    fbb_.AddElement<int32_t>(CS_LOGIN_REQ::VT_TOKEN, token, 0);
  }
  explicit CS_LOGIN_REQBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<CS_LOGIN_REQ> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<CS_LOGIN_REQ>(end);
    return o;
  }
};

inline flatbuffers::Offset<CS_LOGIN_REQ> CreateCS_LOGIN_REQ(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t uid = 0,
    int32_t token = 0) {
  CS_LOGIN_REQBuilder builder_(_fbb);
  builder_.add_uid(uid);
  builder_.add_token(token);
  return builder_.Finish();
}

flatbuffers::Offset<CS_LOGIN_REQ> CreateCS_LOGIN_REQ(flatbuffers::FlatBufferBuilder &_fbb, const CS_LOGIN_REQT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CHARACTER_INFOT : public flatbuffers::NativeTable {
  typedef CHARACTER_INFO TableType;
  int64_t uid = 0;
  std::string name{};
  uint8_t level = 0;
  Define::Job job = Define::Job_WARRIOR;
  std::vector<uint8_t> gear{};
};

struct CHARACTER_INFO FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef CHARACTER_INFOT NativeTableType;
  typedef CHARACTER_INFOBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UID = 4,
    VT_NAME = 6,
    VT_LEVEL = 8,
    VT_JOB = 10,
    VT_GEAR = 12
  };
  int64_t uid() const {
    return GetField<int64_t>(VT_UID, 0);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  uint8_t level() const {
    return GetField<uint8_t>(VT_LEVEL, 0);
  }
  Define::Job job() const {
    return static_cast<Define::Job>(GetField<uint8_t>(VT_JOB, 0));
  }
  const flatbuffers::Vector<uint8_t> *gear() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_GEAR);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_UID) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint8_t>(verifier, VT_LEVEL) &&
           VerifyField<uint8_t>(verifier, VT_JOB) &&
           VerifyOffset(verifier, VT_GEAR) &&
           verifier.VerifyVector(gear()) &&
           verifier.EndTable();
  }
  CHARACTER_INFOT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CHARACTER_INFOT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<CHARACTER_INFO> Pack(flatbuffers::FlatBufferBuilder &_fbb, const CHARACTER_INFOT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CHARACTER_INFOBuilder {
  typedef CHARACTER_INFO Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_uid(int64_t uid) {
    fbb_.AddElement<int64_t>(CHARACTER_INFO::VT_UID, uid, 0);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(CHARACTER_INFO::VT_NAME, name);
  }
  void add_level(uint8_t level) {
    fbb_.AddElement<uint8_t>(CHARACTER_INFO::VT_LEVEL, level, 0);
  }
  void add_job(Define::Job job) {
    fbb_.AddElement<uint8_t>(CHARACTER_INFO::VT_JOB, static_cast<uint8_t>(job), 0);
  }
  void add_gear(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> gear) {
    fbb_.AddOffset(CHARACTER_INFO::VT_GEAR, gear);
  }
  explicit CHARACTER_INFOBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<CHARACTER_INFO> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<CHARACTER_INFO>(end);
    return o;
  }
};

inline flatbuffers::Offset<CHARACTER_INFO> CreateCHARACTER_INFO(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t uid = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    uint8_t level = 0,
    Define::Job job = Define::Job_WARRIOR,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> gear = 0) {
  CHARACTER_INFOBuilder builder_(_fbb);
  builder_.add_uid(uid);
  builder_.add_gear(gear);
  builder_.add_name(name);
  builder_.add_job(job);
  builder_.add_level(level);
  return builder_.Finish();
}

inline flatbuffers::Offset<CHARACTER_INFO> CreateCHARACTER_INFODirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t uid = 0,
    const char *name = nullptr,
    uint8_t level = 0,
    Define::Job job = Define::Job_WARRIOR,
    const std::vector<uint8_t> *gear = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto gear__ = gear ? _fbb.CreateVector<uint8_t>(*gear) : 0;
  return LoginPacket::CreateCHARACTER_INFO(
      _fbb,
      uid,
      name__,
      level,
      job,
      gear__);
}

flatbuffers::Offset<CHARACTER_INFO> CreateCHARACTER_INFO(flatbuffers::FlatBufferBuilder &_fbb, const CHARACTER_INFOT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SC_LOGIN_REST : public flatbuffers::NativeTable {
  typedef SC_LOGIN_RES TableType;
  LoginPacket::ErrorCode result = LoginPacket::ErrorCode_SUCCESS;
  uint8_t max_slot_count = 0;
  uint8_t empty_slot_count = 0;
  std::vector<std::unique_ptr<LoginPacket::CHARACTER_INFOT>> character_info{};
};

struct SC_LOGIN_RES FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SC_LOGIN_REST NativeTableType;
  typedef SC_LOGIN_RESBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RESULT = 4,
    VT_MAX_SLOT_COUNT = 6,
    VT_EMPTY_SLOT_COUNT = 8,
    VT_CHARACTER_INFO = 10
  };
  LoginPacket::ErrorCode result() const {
    return static_cast<LoginPacket::ErrorCode>(GetField<int8_t>(VT_RESULT, 0));
  }
  uint8_t max_slot_count() const {
    return GetField<uint8_t>(VT_MAX_SLOT_COUNT, 0);
  }
  uint8_t empty_slot_count() const {
    return GetField<uint8_t>(VT_EMPTY_SLOT_COUNT, 0);
  }
  const flatbuffers::Vector<flatbuffers::Offset<LoginPacket::CHARACTER_INFO>> *character_info() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<LoginPacket::CHARACTER_INFO>> *>(VT_CHARACTER_INFO);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_RESULT) &&
           VerifyField<uint8_t>(verifier, VT_MAX_SLOT_COUNT) &&
           VerifyField<uint8_t>(verifier, VT_EMPTY_SLOT_COUNT) &&
           VerifyOffset(verifier, VT_CHARACTER_INFO) &&
           verifier.VerifyVector(character_info()) &&
           verifier.VerifyVectorOfTables(character_info()) &&
           verifier.EndTable();
  }
  SC_LOGIN_REST *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SC_LOGIN_REST *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<SC_LOGIN_RES> Pack(flatbuffers::FlatBufferBuilder &_fbb, const SC_LOGIN_REST* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SC_LOGIN_RESBuilder {
  typedef SC_LOGIN_RES Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_result(LoginPacket::ErrorCode result) {
    fbb_.AddElement<int8_t>(SC_LOGIN_RES::VT_RESULT, static_cast<int8_t>(result), 0);
  }
  void add_max_slot_count(uint8_t max_slot_count) {
    fbb_.AddElement<uint8_t>(SC_LOGIN_RES::VT_MAX_SLOT_COUNT, max_slot_count, 0);
  }
  void add_empty_slot_count(uint8_t empty_slot_count) {
    fbb_.AddElement<uint8_t>(SC_LOGIN_RES::VT_EMPTY_SLOT_COUNT, empty_slot_count, 0);
  }
  void add_character_info(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<LoginPacket::CHARACTER_INFO>>> character_info) {
    fbb_.AddOffset(SC_LOGIN_RES::VT_CHARACTER_INFO, character_info);
  }
  explicit SC_LOGIN_RESBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<SC_LOGIN_RES> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SC_LOGIN_RES>(end);
    return o;
  }
};

inline flatbuffers::Offset<SC_LOGIN_RES> CreateSC_LOGIN_RES(
    flatbuffers::FlatBufferBuilder &_fbb,
    LoginPacket::ErrorCode result = LoginPacket::ErrorCode_SUCCESS,
    uint8_t max_slot_count = 0,
    uint8_t empty_slot_count = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<LoginPacket::CHARACTER_INFO>>> character_info = 0) {
  SC_LOGIN_RESBuilder builder_(_fbb);
  builder_.add_character_info(character_info);
  builder_.add_empty_slot_count(empty_slot_count);
  builder_.add_max_slot_count(max_slot_count);
  builder_.add_result(result);
  return builder_.Finish();
}

inline flatbuffers::Offset<SC_LOGIN_RES> CreateSC_LOGIN_RESDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    LoginPacket::ErrorCode result = LoginPacket::ErrorCode_SUCCESS,
    uint8_t max_slot_count = 0,
    uint8_t empty_slot_count = 0,
    const std::vector<flatbuffers::Offset<LoginPacket::CHARACTER_INFO>> *character_info = nullptr) {
  auto character_info__ = character_info ? _fbb.CreateVector<flatbuffers::Offset<LoginPacket::CHARACTER_INFO>>(*character_info) : 0;
  return LoginPacket::CreateSC_LOGIN_RES(
      _fbb,
      result,
      max_slot_count,
      empty_slot_count,
      character_info__);
}

flatbuffers::Offset<SC_LOGIN_RES> CreateSC_LOGIN_RES(flatbuffers::FlatBufferBuilder &_fbb, const SC_LOGIN_REST *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SC_PING_REQT : public flatbuffers::NativeTable {
  typedef SC_PING_REQ TableType;
};

struct SC_PING_REQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SC_PING_REQT NativeTableType;
  typedef SC_PING_REQBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  SC_PING_REQT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SC_PING_REQT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<SC_PING_REQ> Pack(flatbuffers::FlatBufferBuilder &_fbb, const SC_PING_REQT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SC_PING_REQBuilder {
  typedef SC_PING_REQ Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit SC_PING_REQBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<SC_PING_REQ> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SC_PING_REQ>(end);
    return o;
  }
};

inline flatbuffers::Offset<SC_PING_REQ> CreateSC_PING_REQ(
    flatbuffers::FlatBufferBuilder &_fbb) {
  SC_PING_REQBuilder builder_(_fbb);
  return builder_.Finish();
}

flatbuffers::Offset<SC_PING_REQ> CreateSC_PING_REQ(flatbuffers::FlatBufferBuilder &_fbb, const SC_PING_REQT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CS_PING_REST : public flatbuffers::NativeTable {
  typedef CS_PING_RES TableType;
};

struct CS_PING_RES FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef CS_PING_REST NativeTableType;
  typedef CS_PING_RESBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  CS_PING_REST *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CS_PING_REST *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<CS_PING_RES> Pack(flatbuffers::FlatBufferBuilder &_fbb, const CS_PING_REST* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CS_PING_RESBuilder {
  typedef CS_PING_RES Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit CS_PING_RESBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<CS_PING_RES> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<CS_PING_RES>(end);
    return o;
  }
};

inline flatbuffers::Offset<CS_PING_RES> CreateCS_PING_RES(
    flatbuffers::FlatBufferBuilder &_fbb) {
  CS_PING_RESBuilder builder_(_fbb);
  return builder_.Finish();
}

flatbuffers::Offset<CS_PING_RES> CreateCS_PING_RES(flatbuffers::FlatBufferBuilder &_fbb, const CS_PING_REST *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CS_LOGOUT_NOTIT : public flatbuffers::NativeTable {
  typedef CS_LOGOUT_NOTI TableType;
};

struct CS_LOGOUT_NOTI FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef CS_LOGOUT_NOTIT NativeTableType;
  typedef CS_LOGOUT_NOTIBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  CS_LOGOUT_NOTIT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CS_LOGOUT_NOTIT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<CS_LOGOUT_NOTI> Pack(flatbuffers::FlatBufferBuilder &_fbb, const CS_LOGOUT_NOTIT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CS_LOGOUT_NOTIBuilder {
  typedef CS_LOGOUT_NOTI Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit CS_LOGOUT_NOTIBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<CS_LOGOUT_NOTI> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<CS_LOGOUT_NOTI>(end);
    return o;
  }
};

inline flatbuffers::Offset<CS_LOGOUT_NOTI> CreateCS_LOGOUT_NOTI(
    flatbuffers::FlatBufferBuilder &_fbb) {
  CS_LOGOUT_NOTIBuilder builder_(_fbb);
  return builder_.Finish();
}

flatbuffers::Offset<CS_LOGOUT_NOTI> CreateCS_LOGOUT_NOTI(flatbuffers::FlatBufferBuilder &_fbb, const CS_LOGOUT_NOTIT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CS_CREATE_CHARACTER_REQT : public flatbuffers::NativeTable {
  typedef CS_CREATE_CHARACTER_REQ TableType;
  std::string name{};
  Define::Job job = Define::Job_WARRIOR;
};

struct CS_CREATE_CHARACTER_REQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef CS_CREATE_CHARACTER_REQT NativeTableType;
  typedef CS_CREATE_CHARACTER_REQBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_JOB = 6
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  Define::Job job() const {
    return static_cast<Define::Job>(GetField<uint8_t>(VT_JOB, 0));
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint8_t>(verifier, VT_JOB) &&
           verifier.EndTable();
  }
  CS_CREATE_CHARACTER_REQT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CS_CREATE_CHARACTER_REQT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<CS_CREATE_CHARACTER_REQ> Pack(flatbuffers::FlatBufferBuilder &_fbb, const CS_CREATE_CHARACTER_REQT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CS_CREATE_CHARACTER_REQBuilder {
  typedef CS_CREATE_CHARACTER_REQ Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(CS_CREATE_CHARACTER_REQ::VT_NAME, name);
  }
  void add_job(Define::Job job) {
    fbb_.AddElement<uint8_t>(CS_CREATE_CHARACTER_REQ::VT_JOB, static_cast<uint8_t>(job), 0);
  }
  explicit CS_CREATE_CHARACTER_REQBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<CS_CREATE_CHARACTER_REQ> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<CS_CREATE_CHARACTER_REQ>(end);
    return o;
  }
};

inline flatbuffers::Offset<CS_CREATE_CHARACTER_REQ> CreateCS_CREATE_CHARACTER_REQ(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    Define::Job job = Define::Job_WARRIOR) {
  CS_CREATE_CHARACTER_REQBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_job(job);
  return builder_.Finish();
}

inline flatbuffers::Offset<CS_CREATE_CHARACTER_REQ> CreateCS_CREATE_CHARACTER_REQDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    Define::Job job = Define::Job_WARRIOR) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return LoginPacket::CreateCS_CREATE_CHARACTER_REQ(
      _fbb,
      name__,
      job);
}

flatbuffers::Offset<CS_CREATE_CHARACTER_REQ> CreateCS_CREATE_CHARACTER_REQ(flatbuffers::FlatBufferBuilder &_fbb, const CS_CREATE_CHARACTER_REQT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SC_CREATE_CHARACTER_REST : public flatbuffers::NativeTable {
  typedef SC_CREATE_CHARACTER_RES TableType;
  bool is_success = false;
  std::unique_ptr<LoginPacket::CHARACTER_INFOT> character_info{};
};

struct SC_CREATE_CHARACTER_RES FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SC_CREATE_CHARACTER_REST NativeTableType;
  typedef SC_CREATE_CHARACTER_RESBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IS_SUCCESS = 4,
    VT_CHARACTER_INFO = 6
  };
  bool is_success() const {
    return GetField<uint8_t>(VT_IS_SUCCESS, 0) != 0;
  }
  const LoginPacket::CHARACTER_INFO *character_info() const {
    return GetPointer<const LoginPacket::CHARACTER_INFO *>(VT_CHARACTER_INFO);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_IS_SUCCESS) &&
           VerifyOffset(verifier, VT_CHARACTER_INFO) &&
           verifier.VerifyTable(character_info()) &&
           verifier.EndTable();
  }
  SC_CREATE_CHARACTER_REST *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SC_CREATE_CHARACTER_REST *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<SC_CREATE_CHARACTER_RES> Pack(flatbuffers::FlatBufferBuilder &_fbb, const SC_CREATE_CHARACTER_REST* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SC_CREATE_CHARACTER_RESBuilder {
  typedef SC_CREATE_CHARACTER_RES Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_is_success(bool is_success) {
    fbb_.AddElement<uint8_t>(SC_CREATE_CHARACTER_RES::VT_IS_SUCCESS, static_cast<uint8_t>(is_success), 0);
  }
  void add_character_info(flatbuffers::Offset<LoginPacket::CHARACTER_INFO> character_info) {
    fbb_.AddOffset(SC_CREATE_CHARACTER_RES::VT_CHARACTER_INFO, character_info);
  }
  explicit SC_CREATE_CHARACTER_RESBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<SC_CREATE_CHARACTER_RES> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SC_CREATE_CHARACTER_RES>(end);
    return o;
  }
};

inline flatbuffers::Offset<SC_CREATE_CHARACTER_RES> CreateSC_CREATE_CHARACTER_RES(
    flatbuffers::FlatBufferBuilder &_fbb,
    bool is_success = false,
    flatbuffers::Offset<LoginPacket::CHARACTER_INFO> character_info = 0) {
  SC_CREATE_CHARACTER_RESBuilder builder_(_fbb);
  builder_.add_character_info(character_info);
  builder_.add_is_success(is_success);
  return builder_.Finish();
}

flatbuffers::Offset<SC_CREATE_CHARACTER_RES> CreateSC_CREATE_CHARACTER_RES(flatbuffers::FlatBufferBuilder &_fbb, const SC_CREATE_CHARACTER_REST *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct RootT : public flatbuffers::NativeTable {
  typedef Root TableType;
  LoginPacket::PacketUnion packet{};
};

struct Root FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef RootT NativeTableType;
  typedef RootBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PACKET_TYPE = 4,
    VT_PACKET = 6
  };
  LoginPacket::Packet packet_type() const {
    return static_cast<LoginPacket::Packet>(GetField<uint8_t>(VT_PACKET_TYPE, 0));
  }
  const void *packet() const {
    return GetPointer<const void *>(VT_PACKET);
  }
  template<typename T> const T *packet_as() const;
  const LoginPacket::CS_LOGIN_REQ *packet_as_CS_LOGIN_REQ() const {
    return packet_type() == LoginPacket::Packet_CS_LOGIN_REQ ? static_cast<const LoginPacket::CS_LOGIN_REQ *>(packet()) : nullptr;
  }
  const LoginPacket::SC_LOGIN_RES *packet_as_SC_LOGIN_RES() const {
    return packet_type() == LoginPacket::Packet_SC_LOGIN_RES ? static_cast<const LoginPacket::SC_LOGIN_RES *>(packet()) : nullptr;
  }
  const LoginPacket::SC_PING_REQ *packet_as_SC_PING_REQ() const {
    return packet_type() == LoginPacket::Packet_SC_PING_REQ ? static_cast<const LoginPacket::SC_PING_REQ *>(packet()) : nullptr;
  }
  const LoginPacket::CS_PING_RES *packet_as_CS_PING_RES() const {
    return packet_type() == LoginPacket::Packet_CS_PING_RES ? static_cast<const LoginPacket::CS_PING_RES *>(packet()) : nullptr;
  }
  const LoginPacket::CS_LOGOUT_NOTI *packet_as_CS_LOGOUT_NOTI() const {
    return packet_type() == LoginPacket::Packet_CS_LOGOUT_NOTI ? static_cast<const LoginPacket::CS_LOGOUT_NOTI *>(packet()) : nullptr;
  }
  const LoginPacket::CS_CREATE_CHARACTER_REQ *packet_as_CS_CREATE_CHARACTER_REQ() const {
    return packet_type() == LoginPacket::Packet_CS_CREATE_CHARACTER_REQ ? static_cast<const LoginPacket::CS_CREATE_CHARACTER_REQ *>(packet()) : nullptr;
  }
  const LoginPacket::SC_CREATE_CHARACTER_RES *packet_as_SC_CREATE_CHARACTER_RES() const {
    return packet_type() == LoginPacket::Packet_SC_CREATE_CHARACTER_RES ? static_cast<const LoginPacket::SC_CREATE_CHARACTER_RES *>(packet()) : nullptr;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PACKET_TYPE) &&
           VerifyOffset(verifier, VT_PACKET) &&
           VerifyPacket(verifier, packet(), packet_type()) &&
           verifier.EndTable();
  }
  RootT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(RootT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Root> Pack(flatbuffers::FlatBufferBuilder &_fbb, const RootT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const LoginPacket::CS_LOGIN_REQ *Root::packet_as<LoginPacket::CS_LOGIN_REQ>() const {
  return packet_as_CS_LOGIN_REQ();
}

template<> inline const LoginPacket::SC_LOGIN_RES *Root::packet_as<LoginPacket::SC_LOGIN_RES>() const {
  return packet_as_SC_LOGIN_RES();
}

template<> inline const LoginPacket::SC_PING_REQ *Root::packet_as<LoginPacket::SC_PING_REQ>() const {
  return packet_as_SC_PING_REQ();
}

template<> inline const LoginPacket::CS_PING_RES *Root::packet_as<LoginPacket::CS_PING_RES>() const {
  return packet_as_CS_PING_RES();
}

template<> inline const LoginPacket::CS_LOGOUT_NOTI *Root::packet_as<LoginPacket::CS_LOGOUT_NOTI>() const {
  return packet_as_CS_LOGOUT_NOTI();
}

template<> inline const LoginPacket::CS_CREATE_CHARACTER_REQ *Root::packet_as<LoginPacket::CS_CREATE_CHARACTER_REQ>() const {
  return packet_as_CS_CREATE_CHARACTER_REQ();
}

template<> inline const LoginPacket::SC_CREATE_CHARACTER_RES *Root::packet_as<LoginPacket::SC_CREATE_CHARACTER_RES>() const {
  return packet_as_SC_CREATE_CHARACTER_RES();
}

struct RootBuilder {
  typedef Root Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_packet_type(LoginPacket::Packet packet_type) {
    fbb_.AddElement<uint8_t>(Root::VT_PACKET_TYPE, static_cast<uint8_t>(packet_type), 0);
  }
  void add_packet(flatbuffers::Offset<void> packet) {
    fbb_.AddOffset(Root::VT_PACKET, packet);
  }
  explicit RootBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Root> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Root>(end);
    return o;
  }
};

inline flatbuffers::Offset<Root> CreateRoot(
    flatbuffers::FlatBufferBuilder &_fbb,
    LoginPacket::Packet packet_type = LoginPacket::Packet_NONE,
    flatbuffers::Offset<void> packet = 0) {
  RootBuilder builder_(_fbb);
  builder_.add_packet(packet);
  builder_.add_packet_type(packet_type);
  return builder_.Finish();
}

flatbuffers::Offset<Root> CreateRoot(flatbuffers::FlatBufferBuilder &_fbb, const RootT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline CS_LOGIN_REQT *CS_LOGIN_REQ::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CS_LOGIN_REQT>(new CS_LOGIN_REQT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CS_LOGIN_REQ::UnPackTo(CS_LOGIN_REQT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = uid(); _o->uid = _e; }
  { auto _e = token(); _o->token = _e; }
}

inline flatbuffers::Offset<CS_LOGIN_REQ> CS_LOGIN_REQ::Pack(flatbuffers::FlatBufferBuilder &_fbb, const CS_LOGIN_REQT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCS_LOGIN_REQ(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<CS_LOGIN_REQ> CreateCS_LOGIN_REQ(flatbuffers::FlatBufferBuilder &_fbb, const CS_LOGIN_REQT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const CS_LOGIN_REQT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _uid = _o->uid;
  auto _token = _o->token;
  return LoginPacket::CreateCS_LOGIN_REQ(
      _fbb,
      _uid,
      _token);
}

inline CHARACTER_INFOT *CHARACTER_INFO::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CHARACTER_INFOT>(new CHARACTER_INFOT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CHARACTER_INFO::UnPackTo(CHARACTER_INFOT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = uid(); _o->uid = _e; }
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = level(); _o->level = _e; }
  { auto _e = job(); _o->job = _e; }
  { auto _e = gear(); if (_e) { _o->gear.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->gear.begin()); } }
}

inline flatbuffers::Offset<CHARACTER_INFO> CHARACTER_INFO::Pack(flatbuffers::FlatBufferBuilder &_fbb, const CHARACTER_INFOT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCHARACTER_INFO(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<CHARACTER_INFO> CreateCHARACTER_INFO(flatbuffers::FlatBufferBuilder &_fbb, const CHARACTER_INFOT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const CHARACTER_INFOT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _uid = _o->uid;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _level = _o->level;
  auto _job = _o->job;
  auto _gear = _o->gear.size() ? _fbb.CreateVector(_o->gear) : 0;
  return LoginPacket::CreateCHARACTER_INFO(
      _fbb,
      _uid,
      _name,
      _level,
      _job,
      _gear);
}

inline SC_LOGIN_REST *SC_LOGIN_RES::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SC_LOGIN_REST>(new SC_LOGIN_REST());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SC_LOGIN_RES::UnPackTo(SC_LOGIN_REST *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = result(); _o->result = _e; }
  { auto _e = max_slot_count(); _o->max_slot_count = _e; }
  { auto _e = empty_slot_count(); _o->empty_slot_count = _e; }
  { auto _e = character_info(); if (_e) { _o->character_info.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->character_info[_i] = std::unique_ptr<LoginPacket::CHARACTER_INFOT>(_e->Get(_i)->UnPack(_resolver)); } } }
}

inline flatbuffers::Offset<SC_LOGIN_RES> SC_LOGIN_RES::Pack(flatbuffers::FlatBufferBuilder &_fbb, const SC_LOGIN_REST* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSC_LOGIN_RES(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<SC_LOGIN_RES> CreateSC_LOGIN_RES(flatbuffers::FlatBufferBuilder &_fbb, const SC_LOGIN_REST *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const SC_LOGIN_REST* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _result = _o->result;
  auto _max_slot_count = _o->max_slot_count;
  auto _empty_slot_count = _o->empty_slot_count;
  auto _character_info = _o->character_info.size() ? _fbb.CreateVector<flatbuffers::Offset<LoginPacket::CHARACTER_INFO>> (_o->character_info.size(), [](size_t i, _VectorArgs *__va) { return CreateCHARACTER_INFO(*__va->__fbb, __va->__o->character_info[i].get(), __va->__rehasher); }, &_va ) : 0;
  return LoginPacket::CreateSC_LOGIN_RES(
      _fbb,
      _result,
      _max_slot_count,
      _empty_slot_count,
      _character_info);
}

inline SC_PING_REQT *SC_PING_REQ::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SC_PING_REQT>(new SC_PING_REQT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SC_PING_REQ::UnPackTo(SC_PING_REQT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline flatbuffers::Offset<SC_PING_REQ> SC_PING_REQ::Pack(flatbuffers::FlatBufferBuilder &_fbb, const SC_PING_REQT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSC_PING_REQ(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<SC_PING_REQ> CreateSC_PING_REQ(flatbuffers::FlatBufferBuilder &_fbb, const SC_PING_REQT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const SC_PING_REQT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return LoginPacket::CreateSC_PING_REQ(
      _fbb);
}

inline CS_PING_REST *CS_PING_RES::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CS_PING_REST>(new CS_PING_REST());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CS_PING_RES::UnPackTo(CS_PING_REST *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline flatbuffers::Offset<CS_PING_RES> CS_PING_RES::Pack(flatbuffers::FlatBufferBuilder &_fbb, const CS_PING_REST* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCS_PING_RES(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<CS_PING_RES> CreateCS_PING_RES(flatbuffers::FlatBufferBuilder &_fbb, const CS_PING_REST *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const CS_PING_REST* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return LoginPacket::CreateCS_PING_RES(
      _fbb);
}

inline CS_LOGOUT_NOTIT *CS_LOGOUT_NOTI::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CS_LOGOUT_NOTIT>(new CS_LOGOUT_NOTIT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CS_LOGOUT_NOTI::UnPackTo(CS_LOGOUT_NOTIT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline flatbuffers::Offset<CS_LOGOUT_NOTI> CS_LOGOUT_NOTI::Pack(flatbuffers::FlatBufferBuilder &_fbb, const CS_LOGOUT_NOTIT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCS_LOGOUT_NOTI(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<CS_LOGOUT_NOTI> CreateCS_LOGOUT_NOTI(flatbuffers::FlatBufferBuilder &_fbb, const CS_LOGOUT_NOTIT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const CS_LOGOUT_NOTIT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return LoginPacket::CreateCS_LOGOUT_NOTI(
      _fbb);
}

inline CS_CREATE_CHARACTER_REQT *CS_CREATE_CHARACTER_REQ::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CS_CREATE_CHARACTER_REQT>(new CS_CREATE_CHARACTER_REQT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CS_CREATE_CHARACTER_REQ::UnPackTo(CS_CREATE_CHARACTER_REQT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = job(); _o->job = _e; }
}

inline flatbuffers::Offset<CS_CREATE_CHARACTER_REQ> CS_CREATE_CHARACTER_REQ::Pack(flatbuffers::FlatBufferBuilder &_fbb, const CS_CREATE_CHARACTER_REQT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCS_CREATE_CHARACTER_REQ(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<CS_CREATE_CHARACTER_REQ> CreateCS_CREATE_CHARACTER_REQ(flatbuffers::FlatBufferBuilder &_fbb, const CS_CREATE_CHARACTER_REQT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const CS_CREATE_CHARACTER_REQT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _job = _o->job;
  return LoginPacket::CreateCS_CREATE_CHARACTER_REQ(
      _fbb,
      _name,
      _job);
}

inline SC_CREATE_CHARACTER_REST *SC_CREATE_CHARACTER_RES::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SC_CREATE_CHARACTER_REST>(new SC_CREATE_CHARACTER_REST());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SC_CREATE_CHARACTER_RES::UnPackTo(SC_CREATE_CHARACTER_REST *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = is_success(); _o->is_success = _e; }
  { auto _e = character_info(); if (_e) _o->character_info = std::unique_ptr<LoginPacket::CHARACTER_INFOT>(_e->UnPack(_resolver)); }
}

inline flatbuffers::Offset<SC_CREATE_CHARACTER_RES> SC_CREATE_CHARACTER_RES::Pack(flatbuffers::FlatBufferBuilder &_fbb, const SC_CREATE_CHARACTER_REST* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSC_CREATE_CHARACTER_RES(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<SC_CREATE_CHARACTER_RES> CreateSC_CREATE_CHARACTER_RES(flatbuffers::FlatBufferBuilder &_fbb, const SC_CREATE_CHARACTER_REST *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const SC_CREATE_CHARACTER_REST* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _is_success = _o->is_success;
  auto _character_info = _o->character_info ? CreateCHARACTER_INFO(_fbb, _o->character_info.get(), _rehasher) : 0;
  return LoginPacket::CreateSC_CREATE_CHARACTER_RES(
      _fbb,
      _is_success,
      _character_info);
}

inline RootT *Root::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<RootT>(new RootT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Root::UnPackTo(RootT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = packet_type(); _o->packet.type = _e; }
  { auto _e = packet(); if (_e) _o->packet.value = LoginPacket::PacketUnion::UnPack(_e, packet_type(), _resolver); }
}

inline flatbuffers::Offset<Root> Root::Pack(flatbuffers::FlatBufferBuilder &_fbb, const RootT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateRoot(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Root> CreateRoot(flatbuffers::FlatBufferBuilder &_fbb, const RootT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const RootT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _packet_type = _o->packet.type;
  auto _packet = _o->packet.Pack(_fbb);
  return LoginPacket::CreateRoot(
      _fbb,
      _packet_type,
      _packet);
}

inline bool VerifyPacket(flatbuffers::Verifier &verifier, const void *obj, Packet type) {
  switch (type) {
    case Packet_NONE: {
      return true;
    }
    case Packet_CS_LOGIN_REQ: {
      auto ptr = reinterpret_cast<const LoginPacket::CS_LOGIN_REQ *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Packet_SC_LOGIN_RES: {
      auto ptr = reinterpret_cast<const LoginPacket::SC_LOGIN_RES *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Packet_SC_PING_REQ: {
      auto ptr = reinterpret_cast<const LoginPacket::SC_PING_REQ *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Packet_CS_PING_RES: {
      auto ptr = reinterpret_cast<const LoginPacket::CS_PING_RES *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Packet_CS_LOGOUT_NOTI: {
      auto ptr = reinterpret_cast<const LoginPacket::CS_LOGOUT_NOTI *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Packet_CS_CREATE_CHARACTER_REQ: {
      auto ptr = reinterpret_cast<const LoginPacket::CS_CREATE_CHARACTER_REQ *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Packet_SC_CREATE_CHARACTER_RES: {
      auto ptr = reinterpret_cast<const LoginPacket::SC_CREATE_CHARACTER_RES *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyPacketVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPacket(
        verifier,  values->Get(i), types->GetEnum<Packet>(i))) {
      return false;
    }
  }
  return true;
}

inline void *PacketUnion::UnPack(const void *obj, Packet type, const flatbuffers::resolver_function_t *resolver) {
  switch (type) {
    case Packet_CS_LOGIN_REQ: {
      auto ptr = reinterpret_cast<const LoginPacket::CS_LOGIN_REQ *>(obj);
      return ptr->UnPack(resolver);
    }
    case Packet_SC_LOGIN_RES: {
      auto ptr = reinterpret_cast<const LoginPacket::SC_LOGIN_RES *>(obj);
      return ptr->UnPack(resolver);
    }
    case Packet_SC_PING_REQ: {
      auto ptr = reinterpret_cast<const LoginPacket::SC_PING_REQ *>(obj);
      return ptr->UnPack(resolver);
    }
    case Packet_CS_PING_RES: {
      auto ptr = reinterpret_cast<const LoginPacket::CS_PING_RES *>(obj);
      return ptr->UnPack(resolver);
    }
    case Packet_CS_LOGOUT_NOTI: {
      auto ptr = reinterpret_cast<const LoginPacket::CS_LOGOUT_NOTI *>(obj);
      return ptr->UnPack(resolver);
    }
    case Packet_CS_CREATE_CHARACTER_REQ: {
      auto ptr = reinterpret_cast<const LoginPacket::CS_CREATE_CHARACTER_REQ *>(obj);
      return ptr->UnPack(resolver);
    }
    case Packet_SC_CREATE_CHARACTER_RES: {
      auto ptr = reinterpret_cast<const LoginPacket::SC_CREATE_CHARACTER_RES *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline flatbuffers::Offset<void> PacketUnion::Pack(flatbuffers::FlatBufferBuilder &_fbb, const flatbuffers::rehasher_function_t *_rehasher) const {
  switch (type) {
    case Packet_CS_LOGIN_REQ: {
      auto ptr = reinterpret_cast<const LoginPacket::CS_LOGIN_REQT *>(value);
      return CreateCS_LOGIN_REQ(_fbb, ptr, _rehasher).Union();
    }
    case Packet_SC_LOGIN_RES: {
      auto ptr = reinterpret_cast<const LoginPacket::SC_LOGIN_REST *>(value);
      return CreateSC_LOGIN_RES(_fbb, ptr, _rehasher).Union();
    }
    case Packet_SC_PING_REQ: {
      auto ptr = reinterpret_cast<const LoginPacket::SC_PING_REQT *>(value);
      return CreateSC_PING_REQ(_fbb, ptr, _rehasher).Union();
    }
    case Packet_CS_PING_RES: {
      auto ptr = reinterpret_cast<const LoginPacket::CS_PING_REST *>(value);
      return CreateCS_PING_RES(_fbb, ptr, _rehasher).Union();
    }
    case Packet_CS_LOGOUT_NOTI: {
      auto ptr = reinterpret_cast<const LoginPacket::CS_LOGOUT_NOTIT *>(value);
      return CreateCS_LOGOUT_NOTI(_fbb, ptr, _rehasher).Union();
    }
    case Packet_CS_CREATE_CHARACTER_REQ: {
      auto ptr = reinterpret_cast<const LoginPacket::CS_CREATE_CHARACTER_REQT *>(value);
      return CreateCS_CREATE_CHARACTER_REQ(_fbb, ptr, _rehasher).Union();
    }
    case Packet_SC_CREATE_CHARACTER_RES: {
      auto ptr = reinterpret_cast<const LoginPacket::SC_CREATE_CHARACTER_REST *>(value);
      return CreateSC_CREATE_CHARACTER_RES(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline PacketUnion::PacketUnion(const PacketUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case Packet_CS_LOGIN_REQ: {
      value = new LoginPacket::CS_LOGIN_REQT(*reinterpret_cast<LoginPacket::CS_LOGIN_REQT *>(u.value));
      break;
    }
    case Packet_SC_LOGIN_RES: {
      FLATBUFFERS_ASSERT(false);  // LoginPacket::SC_LOGIN_REST not copyable.
      break;
    }
    case Packet_SC_PING_REQ: {
      value = new LoginPacket::SC_PING_REQT(*reinterpret_cast<LoginPacket::SC_PING_REQT *>(u.value));
      break;
    }
    case Packet_CS_PING_RES: {
      value = new LoginPacket::CS_PING_REST(*reinterpret_cast<LoginPacket::CS_PING_REST *>(u.value));
      break;
    }
    case Packet_CS_LOGOUT_NOTI: {
      value = new LoginPacket::CS_LOGOUT_NOTIT(*reinterpret_cast<LoginPacket::CS_LOGOUT_NOTIT *>(u.value));
      break;
    }
    case Packet_CS_CREATE_CHARACTER_REQ: {
      value = new LoginPacket::CS_CREATE_CHARACTER_REQT(*reinterpret_cast<LoginPacket::CS_CREATE_CHARACTER_REQT *>(u.value));
      break;
    }
    case Packet_SC_CREATE_CHARACTER_RES: {
      FLATBUFFERS_ASSERT(false);  // LoginPacket::SC_CREATE_CHARACTER_REST not copyable.
      break;
    }
    default:
      break;
  }
}

inline void PacketUnion::Reset() {
  switch (type) {
    case Packet_CS_LOGIN_REQ: {
      auto ptr = reinterpret_cast<LoginPacket::CS_LOGIN_REQT *>(value);
      delete ptr;
      break;
    }
    case Packet_SC_LOGIN_RES: {
      auto ptr = reinterpret_cast<LoginPacket::SC_LOGIN_REST *>(value);
      delete ptr;
      break;
    }
    case Packet_SC_PING_REQ: {
      auto ptr = reinterpret_cast<LoginPacket::SC_PING_REQT *>(value);
      delete ptr;
      break;
    }
    case Packet_CS_PING_RES: {
      auto ptr = reinterpret_cast<LoginPacket::CS_PING_REST *>(value);
      delete ptr;
      break;
    }
    case Packet_CS_LOGOUT_NOTI: {
      auto ptr = reinterpret_cast<LoginPacket::CS_LOGOUT_NOTIT *>(value);
      delete ptr;
      break;
    }
    case Packet_CS_CREATE_CHARACTER_REQ: {
      auto ptr = reinterpret_cast<LoginPacket::CS_CREATE_CHARACTER_REQT *>(value);
      delete ptr;
      break;
    }
    case Packet_SC_CREATE_CHARACTER_RES: {
      auto ptr = reinterpret_cast<LoginPacket::SC_CREATE_CHARACTER_REST *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = Packet_NONE;
}

inline const LoginPacket::Root *GetRoot(const void *buf) {
  return flatbuffers::GetRoot<LoginPacket::Root>(buf);
}

inline const LoginPacket::Root *GetSizePrefixedRoot(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<LoginPacket::Root>(buf);
}

inline bool VerifyRootBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<LoginPacket::Root>(nullptr);
}

inline bool VerifySizePrefixedRootBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<LoginPacket::Root>(nullptr);
}

inline void FinishRootBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<LoginPacket::Root> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRootBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<LoginPacket::Root> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<LoginPacket::RootT> UnPackRoot(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<LoginPacket::RootT>(GetRoot(buf)->UnPack(res));
}

inline std::unique_ptr<LoginPacket::RootT> UnPackSizePrefixedRoot(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<LoginPacket::RootT>(GetSizePrefixedRoot(buf)->UnPack(res));
}

}  // namespace LoginPacket

#endif  // FLATBUFFERS_GENERATED_LOGINPROTOCOL_LOGINPACKET_H_
