#pragma once

#include "../../Core/Core/CoreInclude.h"
#include "native_info_impl.h"
#include "login_protocol_generated.h"
#include "game_protocol_generated.h"
#include "CharacterData.h"
#include "DataManager.h"
#include "PacketSendManager.h"
#include "LoginPacketFunc.h"
#include "LoginPacketHandler.h"
#include "Character.h"
#include "LoginClient.h"
#include "DummyClientManager.h"
#include "WebManager.h"
