// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Define
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public enum Job : byte
{
  Warrior = 0,
  Archer = 1,
  Sorcerer = 2,
  Duelist = 3,
};

public enum AccountLimit : byte
{
  MinIDLen = 2,
  MinPasswordLen = 4,
  MaxIDLen = 10,
  MaxPasswordLen = 15,
};

public enum CharacterLimit : byte
{
  MinNameLen = 1,
  MaxCharacterSlot = 5,
  MaxNameLen = 8,
};


}
