// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Define
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public enum Job : sbyte
{
  Warrior = 0,
  Archer = 1,
  Sorcerer = 2,
  Duelist = 3,
};


}
