// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Define
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public enum ServerType : byte
{
  WorldList = 0,
  Login = 1,
  Game = 2,
  ServerTypeEnd = 3,
};

public enum Job : byte
{
  WARRIOR = 0,
  ARCHER = 1,
  SORCERER = 2,
  DUELIST = 3,
};

public enum AccountLimit : byte
{
  MinIDLen = 2,
  MinPasswordLen = 4,
  MaxIDLen = 10,
  MaxPasswordLen = 15,
};

public enum CharacterLimit : byte
{
  MinNameLen = 1,
  EmptyCharacterSlot = 3,
  MaxCharacterSlot = 5,
  MaxNameLen = 8,
};

public enum StatType : byte
{
  STR = 0,
  DEX = 1,
  INT = 2,
  STAT_END = 3,
};

public enum Ability : byte
{
  HP = 0,
  MP = 1,
  DAMAGE = 2,
  MAGIC_DAMAGE = 3,
  DEFENCE = 4,
  MAGIC_DEFENCE = 5,
  ATTACK_SPEED = 6,
  MAGIC_CASTING_SPEED = 7,
  MOVE_SPEED = 8,
  CRITICAL_RATE = 9,
  MAGIC_CRITICAL_RATE = 10,
  LIGHT_REGISTTANCE = 11,
  DARK_REGISTTANCE = 12,
  FIRE_REGISTTANCE = 13,
  ICE_REGISTTANCE = 14,
};

public enum AbilityByStatType : byte
{
  HP = 0,
  MP = 1,
  DAMAGE = 2,
  MAGIC_DAMAGE = 3,
  DEFENCE = 4,
  MAGIC_DEFENCE = 5,
  ABILITY_BY_STAT_END = 6,
};

public enum GearType : byte
{
  LEFT_HAND = 0,
  RIGHT_HAND = 1,
  ARMOR = 2,
  HELMET = 3,
  SHOULDER = 4,
  ARM = 5,
  FEET = 6,
  HAIR = 7,
  FACE = 8,
  GEAR_END = 9,
};

public enum Dir : byte
{
  UP = 0,
  DOWN = 1,
  LEFT = 2,
  RIGHT = 3,
};

public enum CreatureState : byte
{
  IDLE = 0,
  WALK = 1,
  RUN = 2,
  JUMP = 3,
  SKILL = 4,
  DEAD = 5,
};

public enum Money : byte
{
  GEM = 0,
  GOLD = 1,
  MONEY_END = 2,
};


}
